// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PFData.proto

package com.ethan.apigatewaytry.pf;

public final class PFData {
  private PFData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PFFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ethan.apigatewaytry.PFFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes fileBytes = 1;</code>
     */
    boolean hasFileBytes();
    /**
     * <code>required bytes fileBytes = 1;</code>
     */
    com.google.protobuf.ByteString getFileBytes();
  }
  /**
   * Protobuf type {@code com.ethan.apigatewaytry.PFFile}
   */
  public  static final class PFFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ethan.apigatewaytry.PFFile)
      PFFileOrBuilder {
    // Use PFFile.newBuilder() to construct.
    private PFFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PFFile() {
      fileBytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PFFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              fileBytes_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ethan.apigatewaytry.pf.PFData.internal_static_com_ethan_apigatewaytry_PFFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ethan.apigatewaytry.pf.PFData.internal_static_com_ethan_apigatewaytry_PFFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ethan.apigatewaytry.pf.PFData.PFFile.class, com.ethan.apigatewaytry.pf.PFData.PFFile.Builder.class);
    }

    private int bitField0_;
    public static final int FILEBYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString fileBytes_;
    /**
     * <code>required bytes fileBytes = 1;</code>
     */
    public boolean hasFileBytes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes fileBytes = 1;</code>
     */
    public com.google.protobuf.ByteString getFileBytes() {
      return fileBytes_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFileBytes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, fileBytes_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, fileBytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ethan.apigatewaytry.pf.PFData.PFFile)) {
        return super.equals(obj);
      }
      com.ethan.apigatewaytry.pf.PFData.PFFile other = (com.ethan.apigatewaytry.pf.PFData.PFFile) obj;

      boolean result = true;
      result = result && (hasFileBytes() == other.hasFileBytes());
      if (hasFileBytes()) {
        result = result && getFileBytes()
            .equals(other.getFileBytes());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFileBytes()) {
        hash = (37 * hash) + FILEBYTES_FIELD_NUMBER;
        hash = (53 * hash) + getFileBytes().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ethan.apigatewaytry.pf.PFData.PFFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ethan.apigatewaytry.pf.PFData.PFFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ethan.apigatewaytry.PFFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ethan.apigatewaytry.PFFile)
        com.ethan.apigatewaytry.pf.PFData.PFFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ethan.apigatewaytry.pf.PFData.internal_static_com_ethan_apigatewaytry_PFFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ethan.apigatewaytry.pf.PFData.internal_static_com_ethan_apigatewaytry_PFFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ethan.apigatewaytry.pf.PFData.PFFile.class, com.ethan.apigatewaytry.pf.PFData.PFFile.Builder.class);
      }

      // Construct using com.ethan.apigatewaytry.pf.PFData.PFFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fileBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ethan.apigatewaytry.pf.PFData.internal_static_com_ethan_apigatewaytry_PFFile_descriptor;
      }

      public com.ethan.apigatewaytry.pf.PFData.PFFile getDefaultInstanceForType() {
        return com.ethan.apigatewaytry.pf.PFData.PFFile.getDefaultInstance();
      }

      public com.ethan.apigatewaytry.pf.PFData.PFFile build() {
        com.ethan.apigatewaytry.pf.PFData.PFFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ethan.apigatewaytry.pf.PFData.PFFile buildPartial() {
        com.ethan.apigatewaytry.pf.PFData.PFFile result = new com.ethan.apigatewaytry.pf.PFData.PFFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileBytes_ = fileBytes_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ethan.apigatewaytry.pf.PFData.PFFile) {
          return mergeFrom((com.ethan.apigatewaytry.pf.PFData.PFFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ethan.apigatewaytry.pf.PFData.PFFile other) {
        if (other == com.ethan.apigatewaytry.pf.PFData.PFFile.getDefaultInstance()) return this;
        if (other.hasFileBytes()) {
          setFileBytes(other.getFileBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFileBytes()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ethan.apigatewaytry.pf.PFData.PFFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ethan.apigatewaytry.pf.PFData.PFFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString fileBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes fileBytes = 1;</code>
       */
      public boolean hasFileBytes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes fileBytes = 1;</code>
       */
      public com.google.protobuf.ByteString getFileBytes() {
        return fileBytes_;
      }
      /**
       * <code>required bytes fileBytes = 1;</code>
       */
      public Builder setFileBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes fileBytes = 1;</code>
       */
      public Builder clearFileBytes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileBytes_ = getDefaultInstance().getFileBytes();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ethan.apigatewaytry.PFFile)
    }

    // @@protoc_insertion_point(class_scope:com.ethan.apigatewaytry.PFFile)
    private static final com.ethan.apigatewaytry.pf.PFData.PFFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ethan.apigatewaytry.pf.PFData.PFFile();
    }

    public static com.ethan.apigatewaytry.pf.PFData.PFFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PFFile>
        PARSER = new com.google.protobuf.AbstractParser<PFFile>() {
      public PFFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PFFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PFFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PFFile> getParserForType() {
      return PARSER;
    }

    public com.ethan.apigatewaytry.pf.PFData.PFFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ethan_apigatewaytry_PFFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ethan_apigatewaytry_PFFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014PFData.proto\022\027com.ethan.apigatewaytry\"" +
      "\033\n\006PFFile\022\021\n\tfileBytes\030\001 \002(\014B$\n\032com.etha" +
      "n.apigatewaytry.pfB\006PFData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ethan_apigatewaytry_PFFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ethan_apigatewaytry_PFFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ethan_apigatewaytry_PFFile_descriptor,
        new java.lang.String[] { "FileBytes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
